# Generated by Django 6.0.3 on 2026-08-20 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('points', 'Points'), ('badge', 'Badge'), ('certificate', 'Certificate'), ('privilege', 'Privilege')], max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('badge_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('behavioral', 'Behavioral'), ('social', 'Social'), ('leadership', 'Leadership'), ('other', 'Other')], max_length=50)),
                ('awarded_date', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_rewards', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'behavioral_rewards',
                'ordering': ['-awarded_date'],
            },
        ),
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('family', 'Family'), ('crisis', 'Crisis Intervention')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=45)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('session_notes', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_sessions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'counseling_sessions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('incident_type', models.CharField(choices=[('bullying', 'Bullying'), ('harassment', 'Harassment'), ('theft', 'Theft'), ('vandalism', 'Vandalism'), ('physical', 'Physical Altercation'), ('verbal', 'Verbal Abuse'), ('cyberbullying', 'Cyberbullying'), ('other', 'Other')], max_length=20)),
                ('incident_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('involved_students', models.JSONField(default=list)),
                ('witnesses', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='reported', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('actions_taken', models.TextField(blank=True)),
                ('investigated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_incidents', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_reports',
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='PositiveBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('helping', 'Helping Others'), ('leadership', 'Leadership'), ('academic', 'Academic Excellence'), ('kindness', 'Kindness'), ('integrity', 'Integrity'), ('other', 'Other')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_positive_behaviors', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positive_behaviors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'positive_behavior_logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailySELCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(choices=[('happy', '😊 Happy'), ('sad', '😢 Sad'), ('excited', '🤩 Excited'), ('tired', '😴 Tired'), ('worried', '😟 Worried'), ('angry', '😠 Angry'), ('calm', '😌 Calm'), ('frustrated', '😤 Frustrated')], max_length=20)),
                ('sleep_quality', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('energy_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('social_interaction', models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('difficult', 'Difficult')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sel_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_sel_checkins',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WellnessTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_period', models.CharField(max_length=20)),
                ('mood_average', models.CharField(blank=True, max_length=20)),
                ('attendance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('academic_performance', models.CharField(blank=True, choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=20)),
                ('social_engagement', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('behavioral_incidents', models.IntegerField(default=0)),
                ('counseling_sessions_count', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('risk_factors', models.JSONField(default=list)),
                ('recommendations', models.TextField(blank=True)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_wellness_trends', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wellness_trends',
                'ordering': ['-analysis_period'],
                'unique_together': {('student', 'analysis_period')},
            },
        ),
    ]
