# Generated by Django 6.0.3 on 2026-08-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('staff', 'Staff'), ('driver', 'Driver'), ('attendant', 'Attendant')], default='student', max_length=10),
        ),
    ]
