# Generated by Django 6.0.3 on 2026-09-04 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('admissions', '0004_admissionapplication_assigned_class_and_more'),
        ('students', '0004_user_achievements_user_allergies_user_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_account', to='admissions.admissionapplication'),
        ),
        migrations.AddField(
            model_name='user',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_status',
            field=models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated')], default='active', max_length=20),
        ),
    ]
