const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)];
const draftKey="anyschool-application-draft",appsKey="anyschool-applications",sessionKey="anyschool-student-session";
const appForm=q("#high-school-application");
if(appForm){let step=1;const saved=JSON.parse(localStorage.getItem(draftKey)||"{}");Object.entries(saved).forEach(([n,v])=>{const f=appForm.elements[n];if(f&&f.type!=="checkbox"&&!["portalPassword","confirmPassword"].includes(n))f.value=v});const titles=["Learner details","School & intake","Parent / guardian","Payment & portal access"];
 const show=()=>{qa(".form-step",appForm).forEach(x=>x.classList.toggle("active",+x.dataset.step===step));qa(".app-steps li").forEach((x,i)=>{x.classList.toggle("active",i+1===step);x.classList.toggle("complete",i+1<step)});q("#step-kicker").textContent=`Step ${step} of 4`;q("#step-title").textContent=titles[step-1];q("#previous-step").hidden=step===1;q("#next-step").hidden=step===4;q("#submit-application").hidden=step!==4};
 const save=()=>{const d=Object.fromEntries(new FormData(appForm));delete d.consent;localStorage.setItem(draftKey,JSON.stringify(d));q("#save-note").textContent="Progress saved"};appForm.addEventListener("input",save);
 q("#next-step").onclick=()=>{const fields=qa("input,select,textarea",q(`.form-step[data-step="${step}"]`));if(!fields.every(f=>f.reportValidity()))return;step++;show()};q("#previous-step").onclick=()=>{step--;show()};
 appForm.onsubmit=e=>{e.preventDefault();if(!appForm.reportValidity())return;const d=Object.fromEntries(new FormData(appForm));if(d.portalPassword!==d.confirmPassword){alert("The portal passwords do not match.");return}const ref=`AH-2027-${Math.floor(1000+Math.random()*9000)}`,apps=JSON.parse(localStorage.getItem(appsKey)||"{}");delete d.confirmPassword;apps[ref]={...d,status:"Under review",paymentStatus:"Paid",date:new Date().toISOString()};localStorage.setItem(appsKey,JSON.stringify(apps));localStorage.removeItem(draftKey);appForm.hidden=true;q(".form-heading").hidden=true;q("#application-complete").hidden=false;q("#application-reference").textContent=ref};show()}
const login=q("#login-form");function showDash(id){q("#student-login").hidden=true;const d=q("#student-dashboard");d.hidden=false;d.style.display="grid";q("#student-id").textContent=id}
if(login)login.onsubmit=e=>{e.preventDefault();const d=new FormData(login),id=String(d.get("studentNumber")).trim().toUpperCase(),pw=String(d.get("password")),apps=JSON.parse(localStorage.getItem(appsKey)||"{}");if(id.startsWith("AH-2027-")&&(!apps[id]||apps[id].portalPassword!==pw)){q("#login-error").textContent="Application reference or password is incorrect.";return}if(id.length<4||pw.length<4){q("#login-error").textContent="Enter a valid student number and a password of at least 4 characters.";return}localStorage.setItem(sessionKey,id);showDash(id);if(id.startsWith("AH-2027-"))panel("applications")};
if(q("#student-dashboard")&&localStorage.getItem(sessionKey))showDash(localStorage.getItem(sessionKey));q("#forgot-password")?.addEventListener("click",()=>q("#login-error").textContent="Please contact the school office to reset your password.");
function panel(name){qa(".side-nav nav button").forEach(x=>x.classList.toggle("active",x.dataset.section===name));qa(".dash-section").forEach(x=>x.classList.toggle("active",x.dataset.panel===name));q("#section-title").textContent=q(`.side-nav nav button[data-section="${name}"] span`)?.textContent||"Overview";q(".side-nav").classList.remove("open")}qa(".side-nav nav button").forEach(b=>b.onclick=()=>panel(b.dataset.section));qa("[data-go]").forEach(b=>b.onclick=()=>panel(b.dataset.go));q("#logout-button")?.addEventListener("click",()=>{localStorage.removeItem(sessionKey);location.reload()});q("#mobile-menu")?.addEventListener("click",()=>q(".side-nav").classList.toggle("open"));q("#print-timetable")?.addEventListener("click",()=>print());q("#download-report")?.addEventListener("click",()=>alert("Report download is ready to connect to the school's records system."));q("#payment-button")?.addEventListener("click",()=>q("#payment-note").textContent="Online payments are ready to connect to the school's payment provider.");
const list=q("#saved-applications");if(list){const apps=Object.entries(JSON.parse(localStorage.getItem(appsKey)||"{}"));list.innerHTML=apps.length?apps.map(([ref,a])=>`<article class="record-card"><div><span class="record-badge">${a.status}</span><h2>${a.firstName} ${a.lastName}</h2><p>${a.level} · ${a.intake} · ${a.boarding}</p><small>Admission decisions will appear here as Accepted or Rejected.</small></div><div><small>Reference</small><strong>${ref}</strong></div><div><small>Payment</small><strong>${a.paymentStatus||"Pending"}</strong></div></article>`).join(""):`<div class="empty-state small-empty"><h2>No applications yet</h2><p>Applications submitted on this device will appear here.</p><a class="primary-button" href="/application.html">Start an application</a></div>`}
