const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)];
const draftKey="anyschool-application-draft",appsKey="anyschool-applications",sessionKey="anyschool-student-session";
const appForm=q("#high-school-application");
if(appForm){let step=1;const saved=JSON.parse(localStorage.getItem(draftKey)||"{}");Object.entries(saved).forEach(([n,v])=>{const f=appForm.elements[n];if(f&&f.type!=="checkbox"&&f.type!=="file"&&!["portalPassword","confirmPassword"].includes(n))f.value=v});const titles=["Learner details","School & intake","Upload documents","Parent / guardian","Payment & portal access"];
 const show=()=>{qa(".form-step",appForm).forEach(x=>x.classList.toggle("active",+x.dataset.step===step));qa(".app-steps li").forEach((x,i)=>{x.classList.toggle("active",i+1===step);x.classList.toggle("complete",i+1<step)});q("#step-kicker").textContent=`Step ${step} of 5`;q("#step-title").textContent=titles[step-1];q("#previous-step").hidden=step===1;q("#next-step").hidden=step===5;q("#submit-application").hidden=step!==5};
 const save=()=>{const d=Object.fromEntries(new FormData(appForm));delete d.consent;localStorage.setItem(draftKey,JSON.stringify(d));q("#save-note").textContent="Progress saved"};appForm.addEventListener("input",save);
 qa('input[type="file"]',appForm).forEach(input=>input.addEventListener("change",()=>{const file=input.files[0];if(file&&file.size>5*1024*1024){input.value="";alert("Each document must be 5 MB or smaller.")}}));
 q("#next-step").onclick=()=>{const fields=qa("input,select,textarea",q(`.form-step[data-step="${step}"]`));if(!fields.every(f=>f.reportValidity()))return;step++;show()};q("#previous-step").onclick=()=>{step--;show()};
 appForm.onsubmit=e=>{e.preventDefault();if(!appForm.reportValidity())return;const d=Object.fromEntries(new FormData(appForm));if(d.portalPassword!==d.confirmPassword){alert("The portal passwords do not match.");return}const documents=["birthCertificate","schoolReport","passportPhoto","supportingDocument"].map(n=>({type:n,name:appForm.elements[n].files[0]?.name||""})).filter(x=>x.name),ref=`AH-2027-${Math.floor(1000+Math.random()*9000)}`,apps=JSON.parse(localStorage.getItem(appsKey)||"{}");delete d.confirmPassword;documents.forEach(x=>delete d[x.type]);apps[ref]={...d,documents,status:"Under review",paymentStatus:"Paid",date:new Date().toISOString()};localStorage.setItem(appsKey,JSON.stringify(apps));localStorage.removeItem(draftKey);appForm.hidden=true;q(".form-heading").hidden=true;q("#application-complete").hidden=false;q("#application-reference").textContent=ref};show()}
const login=q("#login-form");function showDash(id){q("#student-login").hidden=true;const d=q("#student-dashboard");d.hidden=false;d.style.display="grid";q("#student-id").textContent=id}
if(login)login.onsubmit=e=>{e.preventDefault();const d=new FormData(login),id=String(d.get("studentNumber")).trim().toUpperCase(),pw=String(d.get("password")),apps=JSON.parse(localStorage.getItem(appsKey)||"{}");if(id.startsWith("AH-2027-")&&(!apps[id]||apps[id].portalPassword!==pw)){q("#login-error").textContent="Application reference or password is incorrect.";return}if(id.length<4||pw.length<4){q("#login-error").textContent="Enter a valid student number and a password of at least 4 characters.";return}localStorage.setItem(sessionKey,id);showDash(id);if(id.startsWith("AH-2027-"))panel("applications")};
if(q("#student-dashboard")&&localStorage.getItem(sessionKey))showDash(localStorage.getItem(sessionKey));q("#forgot-password")?.addEventListener("click",()=>q("#login-error").textContent="Please contact the school office to reset your password.");
function panel(name){qa(".side-nav nav button").forEach(x=>x.classList.toggle("active",x.dataset.section===name));qa(".dash-section").forEach(x=>x.classList.toggle("active",x.dataset.panel===name));q("#section-title").textContent=q(`.side-nav nav button[data-section="${name}"] span`)?.textContent||"Overview";q(".side-nav").classList.remove("open")}qa(".side-nav nav button").forEach(b=>b.onclick=()=>panel(b.dataset.section));qa("[data-go]").forEach(b=>b.onclick=()=>panel(b.dataset.go));q("#logout-button")?.addEventListener("click",()=>{localStorage.removeItem(sessionKey);location.reload()});q("#mobile-menu")?.addEventListener("click",()=>q(".side-nav").classList.toggle("open"));q("#print-timetable")?.addEventListener("click",()=>print());q("#download-report")?.addEventListener("click",()=>alert("Report download is ready to connect to the school's records system."));q("#payment-button")?.addEventListener("click",()=>q("#payment-note").textContent="Online payments are ready to connect to the school's payment provider.");
const list=q("#saved-applications");if(list){const apps=Object.entries(JSON.parse(localStorage.getItem(appsKey)||"{}"));list.innerHTML=apps.length?apps.map(([ref,a])=>`<article class="record-card"><div><span class="record-badge">${a.status}</span><h2>${a.firstName} ${a.lastName}</h2><p>${a.level} · ${a.intake} · ${a.boarding}</p><small>Admission decisions will appear here as Accepted or Rejected.</small></div><div><small>Reference</small><strong>${ref}</strong></div><div><small>Payment</small><strong>${a.paymentStatus||"Pending"}</strong></div></article>`).join(""):`<div class="empty-state small-empty"><h2>No applications yet</h2><p>Applications submitted on this device will appear here.</p><a class="primary-button" href="/application.html">Start an application</a></div>`}

const adminLogin=q("#admin-login-form"),adminDash=q("#admin-dashboard");
function renderAdmin(){const target=q("#admin-applications");if(!target)return;const apps=JSON.parse(localStorage.getItem(appsKey)||"{}"),term=(q("#admin-search")?.value||"").toLowerCase(),entries=Object.entries(apps).filter(([ref,a])=>(ref+" "+a.firstName+" "+a.lastName).toLowerCase().includes(term));q("#admin-total").textContent=Object.keys(apps).length;q("#admin-review").textContent=Object.values(apps).filter(a=>a.status==="Under review").length;q("#admin-accepted").textContent=Object.values(apps).filter(a=>a.status==="Accepted").length;q("#admin-rejected").textContent=Object.values(apps).filter(a=>a.status==="Rejected").length;target.innerHTML=entries.length?entries.map(([ref,a])=>`<article class="admin-application"><div><span class="decision-status ${a.status.toLowerCase().replace(" ","-")}">${a.status}</span><h3>${a.firstName} ${a.lastName}</h3><p>${ref} · ${a.level} · ${a.intake}</p></div><div><small>Application fee</small><strong>${a.paymentStatus||"Pending"}</strong><button data-payment="${ref}">${a.paymentStatus==="Paid"?"Mark unpaid":"Confirm paid"}</button></div><div class="decision-actions"><button class="accept-button" data-decision="Accepted" data-ref="${ref}">Accept</button><button class="reject-button" data-decision="Rejected" data-ref="${ref}">Reject</button></div></article>`).join(""):`<div class="empty-state small-empty"><h2>No applications found</h2><p>Submit an application first or change your search.</p></div>`}
if(adminLogin)adminLogin.onsubmit=e=>{e.preventDefault();const d=new FormData(adminLogin);if(d.get("username")!=="admin"||d.get("password")!=="admin123"){q("#admin-error").textContent="Incorrect demo username or password.";return}sessionStorage.setItem("admissions-admin","true");q("#admin-login").hidden=true;adminDash.hidden=false;renderAdmin()};
if(adminDash&&sessionStorage.getItem("admissions-admin")==="true"){q("#admin-login").hidden=true;adminDash.hidden=false;renderAdmin()}
q("#admin-logout")?.addEventListener("click",()=>{sessionStorage.removeItem("admissions-admin");location.reload()});q("#admin-search")?.addEventListener("input",renderAdmin);
q("#admin-applications")?.addEventListener("click",e=>{const decision=e.target.dataset.decision,ref=e.target.dataset.ref,payment=e.target.dataset.payment,apps=JSON.parse(localStorage.getItem(appsKey)||"{}");if(decision&&apps[ref]){apps[ref].status=decision;apps[ref].decisionDate=new Date().toISOString()}if(payment&&apps[payment])apps[payment].paymentStatus=apps[payment].paymentStatus==="Paid"?"Pending":"Paid";localStorage.setItem(appsKey,JSON.stringify(apps));renderAdmin()});
let activeApplicant="";
function renderApplicant(){const apps=JSON.parse(localStorage.getItem(appsKey)||"{}"),a=apps[activeApplicant];if(!a)return;q("#applicant-name").textContent=`${a.firstName} ${a.lastName}`;q("#applicant-reference").textContent=activeApplicant;q("#applicant-decision").textContent=a.status;q("#applicant-decision").className=a.status.toLowerCase().replace(" ","-");q("#applicant-payment").textContent=a.paymentStatus||"Pending";q("#applicant-pay").hidden=a.paymentStatus==="Paid";q("#payment-stage").classList.toggle("done",a.paymentStatus==="Paid");q("#review-stage").classList.add("done");q("#decision-stage").classList.toggle("done",["Accepted","Rejected"].includes(a.status));q("#decision-message").textContent=a.status==="Accepted"?"Congratulations. You have been offered a place.":a.status==="Rejected"?"This application was not successful. Contact admissions for guidance.":"The admissions team is reviewing your information.";q("#submitted-date").textContent=new Date(a.date).toLocaleDateString();q("#applicant-details").innerHTML=`<p><span>Applying for</span><strong>${a.level}</strong></p><p><span>Intake</span><strong>${a.intake}</strong></p><p><span>Placement</span><strong>${a.boarding}</strong></p><p><span>Guardian</span><strong>${a.guardianName}</strong></p>`}
q("#applicant-login-form")?.addEventListener("submit",e=>{e.preventDefault();const d=new FormData(e.currentTarget),ref=String(d.get("reference")).trim().toUpperCase(),apps=JSON.parse(localStorage.getItem(appsKey)||"{}");if(!apps[ref]||apps[ref].portalPassword!==String(d.get("password"))){q("#applicant-error").textContent="Application reference or password is incorrect.";return}activeApplicant=ref;sessionStorage.setItem("active-applicant",ref);q("#applicant-login").hidden=true;q("#applicant-dashboard").hidden=false;renderApplicant()});
if(q("#applicant-dashboard")&&sessionStorage.getItem("active-applicant")){activeApplicant=sessionStorage.getItem("active-applicant");q("#applicant-login").hidden=true;q("#applicant-dashboard").hidden=false;renderApplicant()}
q("#applicant-logout")?.addEventListener("click",()=>{sessionStorage.removeItem("active-applicant");location.reload()});q("#applicant-pay")?.addEventListener("click",()=>{const apps=JSON.parse(localStorage.getItem(appsKey)||"{}");apps[activeApplicant].paymentStatus="Paid";apps[activeApplicant].paymentReference=`PAY-${Date.now().toString().slice(-6)}`;localStorage.setItem(appsKey,JSON.stringify(apps));renderApplicant()});
