# Generated by Django 6.0.3 on 2026-08-20 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'time_slots',
                'ordering': ['day', 'start_time'],
                'unique_together': {('day', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer'), ('winter', 'Winter')], max_length=10)),
                ('academic_year', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.timeslot')),
            ],
            options={
                'db_table': 'schedules',
                'ordering': ['academic_year', 'semester', 'time_slot'],
                'unique_together': {('course', 'time_slot', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ClassConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('schedule1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_first', to='schedule.schedule')),
                ('schedule2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_second', to='schedule.schedule')),
            ],
            options={
                'db_table': 'class_conflicts',
                'unique_together': {('schedule1', 'schedule2', 'conflict_type')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10)),
                ('academic_year', models.CharField(max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timetables',
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('user', 'semester', 'academic_year')},
            },
        ),
    ]
