# Generated by Django 6.0.3 on 2026-09-04 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('schedule', '0001_initial'),
        ('staff', '0002_staffprofile_email_staffprofile_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, help_text="Defaults to the classroom's own room if left blank", max_length=50)),
                ('academic_year', models.CharField(max_length=10)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods', to='staff.staffprofile')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_periods', to='schedule.timeslot')),
            ],
            options={
                'db_table': 'class_periods',
                'ordering': ['time_slot__day', 'time_slot__start_time'],
                'unique_together': {('classroom', 'time_slot', 'academic_year')},
            },
        ),
    ]
