# Generated by Django 6.0.3 on 2026-08-20 16:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('unit_test', 'Unit Test'), ('mid_term', 'Mid Term'), ('final', 'Final Exam'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('grade_level', models.CharField(max_length=10)),
                ('academic_year', models.CharField(max_length=10)),
                ('total_marks', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('paper_type', models.CharField(choices=[('randomized', 'Randomized'), ('fixed', 'Fixed')], default='fixed', max_length=20)),
                ('question_count', models.IntegerField()),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('grade_level', models.CharField(max_length=10)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='examinations.exampaper')),
                ('invigilator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_schedules',
                'ordering': ['exam_date'],
            },
        ),
        migrations.CreateModel(
            name='OnlineExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('proctoring_type', models.CharField(choices=[('none', 'No Proctoring'), ('auto', 'Auto Proctoring'), ('live', 'Live Proctoring')], default='none', max_length=20)),
                ('max_attempts', models.IntegerField(default=1)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='examinations.exampaper')),
            ],
            options={
                'db_table': 'online_exams',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='OnlineExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('time_taken', models.IntegerField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('proctoring_logs', models.JSONField(default=list)),
                ('online_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='examinations.onlineexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'online_exam_attempts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('fill_blank', 'Fill in the Blank')], max_length=20)),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('history', 'History'), ('geography', 'Geography'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('computer_science', 'Computer Science'), ('other', 'Other')], max_length=20)),
                ('chapter', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_bank',
                'ordering': ['subject', 'chapter', 'topic'],
            },
        ),
        migrations.CreateModel(
            name='StudentExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_marks', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.examschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_exam_results',
                'ordering': ['-exam_schedule__exam_date'],
                'unique_together': {('exam_schedule', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ReEvaluationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('original_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('revised_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fee_paid', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_re_evaluations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_evaluation_requests', to=settings.AUTH_USER_MODEL)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_evaluation_requests', to='examinations.studentexamresult')),
            ],
            options={
                'db_table': 're_evaluation_requests',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examinations.exampaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='examinations.questionbank')),
            ],
            options={
                'db_table': 'exam_questions',
                'ordering': ['question_number'],
                'unique_together': {('exam_paper', 'question_number')},
            },
        ),
    ]
