# Generated by Django 6.0.3 on 2026-09-05 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_staffprofile_email_staffprofile_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('sport', 'Sport'), ('academic', 'Academic'), ('cultural', 'Cultural'), ('community', 'Community service'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('meeting_day', models.CharField(blank=True, help_text='e.g. Wednesday', max_length=20)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_coached', to='staff.staffprofile')),
            ],
            options={
                'db_table': 'clubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('school', 'School'), ('district', 'District'), ('provincial', 'Provincial'), ('national', 'National'), ('international', 'International')], default='school', max_length=20)),
                ('date_achieved', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_achievements', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='clubs.club')),
            ],
            options={
                'db_table': 'club_achievements',
                'ordering': ['-date_achieved'],
            },
        ),
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('fixture', 'Fixture/Match'), ('competition', 'Competition'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=20)),
                ('opponent', models.CharField(blank=True, max_length=200)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('event_date', models.DateTimeField()),
                ('our_score', models.IntegerField(blank=True, null=True)),
                ('opponent_score', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.club')),
            ],
            options={
                'db_table': 'club_events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('vice_captain', 'Vice-captain'), ('captain', 'Captain')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'club_memberships',
                'ordering': ['-joined_date'],
                'unique_together': {('club', 'student')},
            },
        ),
    ]
