# Generated by Django 6.0.3 on 2026-08-20 16:34

import admissions.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('grade_applying_for', models.CharField(choices=[('KG', 'Kindergarten'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=10)),
                ('academic_year', models.CharField(choices=[('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], max_length=10)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_address', models.TextField()),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_grade', models.CharField(blank=True, max_length=10)),
                ('transfer_certificate', models.FileField(blank=True, upload_to=admissions.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('admitted', 'Admitted'), ('enrolled', 'Enrolled')], default='draft', max_length=20)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('merit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('admission_letter', models.FileField(blank=True, upload_to=admissions.models.upload_to)),
                ('fee_quotation', models.FileField(blank=True, upload_to=admissions.models.upload_to)),
                ('birth_certificate', models.FileField(blank=True, upload_to=admissions.models.upload_to)),
                ('photo', models.ImageField(blank=True, upload_to=admissions.models.upload_to)),
                ('aadhar_card', models.FileField(blank=True, upload_to=admissions.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admission_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to=admissions.models.upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admissionapplication')),
            ],
            options={
                'db_table': 'admission_documents',
            },
        ),
        migrations.CreateModel(
            name='MeritList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('grade_level', models.CharField(max_length=10)),
                ('cutoff_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_seats', models.IntegerField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'merit_lists',
                'unique_together': {('academic_year', 'grade_level')},
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('estimated_admission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('promoted', 'Promoted'), ('expired', 'Expired')], default='active', max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admissions.admissionapplication')),
            ],
            options={
                'db_table': 'waitlists',
                'ordering': ['position'],
            },
        ),
    ]
