# Generated by Django 6.0.3 on 2026-09-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='academic_year',
            field=models.CharField(choices=[('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028')], max_length=10),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='grade_applying_for',
            field=models.CharField(choices=[('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4'), ('lower6', 'Lower 6'), ('upper6', 'Upper 6')], max_length=10),
        ),
    ]
