# Generated by Django 6.0.3 on 2026-09-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissionapplication_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='portal_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
