# Generated by Django 6.0.3 on 2026-09-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admissionapplication_portal_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='assigned_class',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
