@extends('layouts.site')

@section('title', 'Anyschool High School | Learn. Lead. Serve.')
@section('meta_description', 'Learning with purpose, character and ambition.')
@section('body_page', 'home')

@section('content')
<section class="hero home-hero"><div class="hero-shape hero-shape-one"></div><div class="hero-shape hero-shape-two"></div><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">Knowledge · Character · Community</p><h1>Preparing young people to <em>shape tomorrow.</em></h1><p class="hero-lead">A supportive secondary school where every learner is challenged to think deeply, act with integrity and discover their path.</p><div class="button-row"><a class="btn btn-gold" href="/admissions#apply">Start an application →</a><a class="btn btn-ghost" href="/about">Discover our school</a></div><div class="hero-proof"><span><b>✓</b> Qualified educators</span><span><b>✓</b> Broad curriculum</span><span><b>✓</b> Safe community</span></div></div><aside class="hero-card"><div class="hero-card-top"><span>Admissions</span><strong>2027</strong></div><div class="date-item"><span class="date-box"><b>01</b><small>JUL</small></span><div><strong>Applications open</strong><small>Forms 1–6</small></div></div><div class="date-item"><span class="date-box"><b>30</b><small>SEP</small></span><div><strong>Priority deadline</strong><small>Early applications encouraged</small></div></div><a href="/admissions">View the process →</a></aside></div><div class="container stats-strip"><div><strong data-count="4">0</strong><span>Learning pathways</span></div><div><strong data-count="20">0</strong><span>Subjects offered</span></div><div><strong data-count="12">0</strong><span>Clubs &amp; activities</span></div><div><strong data-count="1">0</strong><span>Shared community</span></div></div></section>
<section class="section intro"><div class="container split"><div><p class="eyebrow dark">Welcome to Anyschool</p><h2>A school where potential becomes purpose.</h2></div><div class="prose"><p>Strong education develops the whole person. Learners build academic confidence, practical skills, resilience and responsibility to others.</p><p>High expectations and genuine encouragement create a culture where young people can thrive.</p><a class="text-link" href="/about">Get to know us →</a></div></div></section>
<section class="section programmes"><div class="container section-head"><div><p class="eyebrow">Explore Anyschool</p><h2>Everything you need, in the right place.</h2></div><p>Each area now has its own focused page, making the website easier to navigate.</p></div><div class="container home-links"><a href="/academics"><span>01</span><h3>Academics</h3><p>Curriculum, pathways and learning support.</p><b>Explore →</b></a><a href="/student-life"><span>02</span><h3>Student life</h3><p>Sport, culture, clubs and leadership.</p><b>Explore →</b></a><a href="/admissions"><span>03</span><h3>Admissions</h3><p>Requirements, process and online application.</p><b>Explore →</b></a></div></section>
<section class="section news"><div class="container section-head"><div><p class="eyebrow dark">Latest update</p><h2>Applications for 2027 are open.</h2></div><p>Families can now begin the admissions process online and save a reference for tracking.</p></div><div class="container home-cta"><div><p class="eyebrow">Take the next step</p><h2>Could Anyschool be the right fit?</h2></div><div class="button-row"><a class="btn btn-gold" href="/admissions#apply">Apply online →</a><a class="btn btn-ghost" href="/contact">Ask a question</a></div></div></section>
@endsection
