# Generated by Django 6.0.3 on 2026-08-20 16:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('pieces', 'Pieces'), ('kg', 'Kilograms'), ('liters', 'Liters'), ('boxes', 'Boxes'), ('packs', 'Packs'), ('reams', 'Reams')], max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_stock', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_restocked', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consumable_inventory',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('laboratory', 'Laboratory Equipment'), ('sports', 'Sports Equipment'), ('stationery', 'Stationery'), ('books', 'Books'), ('consumables', 'Consumables'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('disposed', 'Disposed')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='assets/qrcodes/')),
                ('barcode', models.CharField(blank=True, max_length=50, unique=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='AssetCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('checked_out', 'Checked Out'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='checked_out', max_length=20)),
                ('condition_on_checkout', models.TextField(blank=True)),
                ('condition_on_return', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='inventory.asset')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_asset_checkouts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_checkouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_checkouts',
                'ordering': ['-checkout_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetUsageAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_usage_date', models.DateTimeField(auto_now=True)),
                ('usage_frequency', models.IntegerField(default=0)),
                ('average_usage_duration', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('maintenance_count', models.IntegerField(default=0)),
                ('failure_prediction', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_analytics', to='inventory.asset')),
            ],
            options={
                'db_table': 'asset_usage_analytics',
            },
        ),
        migrations.CreateModel(
            name='ConsumableTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('adjustment', 'Adjustment'), ('damaged', 'Damaged')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.consumableinventory')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consumable_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='inventory.asset')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_requests',
                'ordering': ['-reported_date'],
            },
        ),
    ]
