# Generated by Django 6.0.3 on 2026-08-20 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceKiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiosk_id', models.CharField(max_length=50, unique=True)),
                ('kiosk_name', models.CharField(max_length=200)),
                ('kiosk_type', models.CharField(choices=[('main_gate', 'Main Gate'), ('classroom', 'Classroom'), ('bus_stop', 'Bus Stop'), ('cafeteria', 'Cafeteria')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('supports_biometric', models.BooleanField(default=False)),
                ('supports_gps', models.BooleanField(default=False)),
                ('supports_offline', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance_kiosks',
                'ordering': ['kiosk_name'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='biometric_data',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='gps_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='offline_device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='offline_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='verification_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('biometric', 'Biometric'), ('fingerprint', 'Fingerprint'), ('facial_recognition', 'Facial Recognition'), ('rfid', 'RFID Card'), ('gps', 'GPS Geofencing'), ('offline', 'Offline Capture')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='attendance_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('biometric', 'Biometric'), ('fingerprint', 'Fingerprint'), ('facial_recognition', 'Facial Recognition'), ('rfid', 'RFID Card'), ('gps', 'GPS Geofencing'), ('offline', 'Offline Capture')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='geofence_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='geofence_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='geofence_radius',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='chronic_absent_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='improvement_trend',
            field=models.CharField(blank=True, choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('absence', 'Absence Alert'), ('late', 'Late Arrival'), ('leave', 'Leave Notification'), ('weekly_summary', 'Weekly Summary'), ('monthly_summary', 'Monthly Summary')], max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_attendance_notifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_type', models.CharField(choices=[('fingerprint', 'Fingerprint'), ('face', 'Face Recognition'), ('iris', 'Iris Scan'), ('voice', 'Voice Recognition')], max_length=20)),
                ('template_data', models.TextField()),
                ('device_id', models.CharField(max_length=100)),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biometric_templates',
                'unique_together': {('user', 'biometric_type', 'device_id')},
            },
        ),
    ]
