# Generated by Django 6.0.3 on 2026-08-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpermission',
            options={'ordering': ['-granted_at']},
        ),
    ]
