# Generated by Django 6.0.3 on 2026-08-20 16:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('gps_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'buses',
                'ordering': ['bus_number'],
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=20, unique=True)),
                ('route_name', models.CharField(max_length=200)),
                ('start_point', models.CharField(max_length=200)),
                ('end_point', models.CharField(max_length=200)),
                ('total_distance', models.DecimalField(decimal_places=2, help_text='Distance in km', max_digits=10)),
                ('estimated_duration', models.IntegerField(help_text='Duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bus_routes',
                'ordering': ['route_number'],
            },
        ),
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('police_clearance_expiry', models.DateField(blank=True, null=True)),
                ('medical_clearance_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendant_profile', to=settings.AUTH_USER_MODEL)),
                ('assigned_bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendants', to='transportation.bus')),
            ],
            options={
                'db_table': 'attendants',
            },
        ),
        migrations.CreateModel(
            name='BusFuelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_date', models.DateField()),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('cng', 'CNG'), ('electric', 'Electric')], max_length=20)),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_per_liter', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer_reading', models.IntegerField()),
                ('fuel_station', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_expenses', to='transportation.bus')),
            ],
            options={
                'db_table': 'bus_fuel_expenses',
                'ordering': ['-fuel_date'],
            },
        ),
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='transportation.bus')),
            ],
            options={
                'db_table': 'bus_locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BusMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Maintenance'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('emergency', 'Emergency Repair')], max_length=20)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenance_date', models.DateField()),
                ('completed_by', models.CharField(max_length=200)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='transportation.bus')),
            ],
            options={
                'db_table': 'bus_maintenance',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='transportation.busroute'),
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_number', models.IntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_geofence_radius', models.IntegerField(default=100, help_text='Radius in meters')),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transportation.busroute')),
            ],
            options={
                'db_table': 'bus_stops',
                'ordering': ['stop_number'],
                'unique_together': {('route', 'stop_number')},
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry_date', models.DateField()),
                ('license_status', models.CharField(choices=[('valid', 'Valid'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired')], default='valid', max_length=20)),
                ('experience_years', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('police_clearance_expiry', models.DateField(blank=True, null=True)),
                ('medical_clearance_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='transportation.bus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='StudentBusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('card_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('card_type', models.CharField(choices=[('rfid', 'RFID'), ('barcode', 'Barcode'), ('qr', 'QR Code')], default='rfid', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='transportation.bus')),
                ('dropoff_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_students', to='transportation.busstop')),
                ('pickup_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_students', to='transportation.busstop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_bus_assignments',
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
